# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:
  #adapter: sqlite3
  #database: db/development.sqlite3
  #pool: 5
  #timeout: 5000

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: manageracb_development
  pool:     5
  username: manageracb
  password:
  template: template0

staging:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: manageracb_staging
  pool:     5
  username: manageracb
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: manageracb_test
  pool:     5
  username: manageracb
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: manageracb_production
  pool:     5
  username: manageracb
  password:
  template: template0